### ISSUE TITLE
Turn speaker on

### ISSUE THREAD

**Issue by Seblon1** [lakshmansha/cordova-plugin-phone-call#2]
First of all thanks for this plugin.

Is it possible to start a call with speaker switched on automatically?

**Comment by lakshmansha** [comment]
Sorry for Delay on replay. Thank you.

Let me check and add a feature to call with speaker option.

**Comment by lakshmansha** [comment]
Added The Features & Tested on Android. Unable to Test with iOS.

**Comment by lakshmansha** [comment]
@Seblon1 I don't have time to complete it currently i have completed the Speaker-On. If you need any feature let us know.
