### ISSUE TITLE
xcodebuild: Command failed with exit code 65

### ISSUE THREAD

**Issue by loranBepatient** [lakshmansha/cordova-plugin-phone-call#5]
Helle dear Devs ! 

Since today, we are experiencing an issue with the ios version of the plugin. 

We are using `Cordova 9.0.0 (cordova-lib@9.0.1)` 
and 
`cordova-plugin-phone-call 1.1.2 "PhoneCall"`

Xcode is Version 11.4.1 (11E503a)

When building our application with the command `cordova build ios` we get this output: 
``` 
The following build commands failed:
        CompileC /Users/lo/Library/Developer/Xcode/DerivedData/XXXXXX-csfxukfrxvcjecbmrqpffuxhrgys/Build/Intermediates.noindex/XXXXXX.build/Debug-iphonesimulator/XXXXXX.build/Objects-normal/x86_64/PhoneDialer.o /Users/lo/dev/app-ionic/XXXXXX-app/platforms/ios/XXXXXX/Plugins/cordova-plugin-phone-call/PhoneDialer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

```

Also Xcode displays some errors when opening Phonedialer.m

`/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:60:9: error: use of undeclared identifier 'AVAudioSession'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
        ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:60:25: error: use of undeclared identifier 'sessionInstance'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
                        ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:60:44: error: use of undeclared identifier 'AVAudioSession'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
                                           ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:70:73: error: property 'lowercaseString' not found on object of type 'id'
            NSString* IsSpeakerOn = [command.arguments objectAtIndex:2].lowercaseString;     
                                                                        ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:78:29: warning: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid. [-Wdeprecated-declarations]
                    [number stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
                            ^
In module 'Foundation' imported from /Users/lo/Library/Developer/Xcode/DerivedData/bepatient-csfxukfrxvcjecbmrqpffuxhrgys/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAppDelegate.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:588:1: note: 'stringByAddingPercentEscapesUsingEncoding:' has been explicitly marked deprecated here
- (nullable NSString *)stringByAddingPercentEscapesUsingEncoding:(NSStringEncoding)enc API_DEPRECATED("Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.", macos(10.0,10.11), ios(2.0,9.0), watchos(2.0,2.0), tvos(9.0,9.0));
^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:85:61: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                else if(![[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]]) {
                                                            ^~~~~~~
                                                            openURL:options:completionHandler:
In module 'UIKit' imported from /Users/lo/Library/Developer/Xcode/DerivedData/bepatient-csfxukfrxvcjecbmrqpffuxhrgys/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
- (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:93:22: error: use of undeclared identifier 'sessionInstance'
                    [sessionInstance overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:nil];  
                     ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:96:22: error: use of undeclared identifier 'sessionInstance'
                    [sessionInstance overrideOutputAudioPort:AVAudioSessionPortOverrideNone error:&error];
                     ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:117:9: error: use of undeclared identifier 'AVAudioSession'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
        ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:117:25: error: use of undeclared identifier 'sessionInstance'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
                        ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:117:44: error: use of undeclared identifier 'AVAudioSession'
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
                                           ^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:134:29: warning: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid. [-Wdeprecated-declarations]
                    [number stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
                            ^
In module 'Foundation' imported from /Users/lo/Library/Developer/Xcode/DerivedData/bepatient-csfxukfrxvcjecbmrqpffuxhrgys/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAppDelegate.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:588:1: note: 'stringByAddingPercentEscapesUsingEncoding:' has been explicitly marked deprecated here
- (nullable NSString *)stringByAddingPercentEscapesUsingEncoding:(NSStringEncoding)enc API_DEPRECATED("Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.", macos(10.0,10.11), ios(2.0,9.0), watchos(2.0,2.0), tvos(9.0,9.0));
^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:141:61: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                else if(![[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]]) {
                                                            ^~~~~~~
                                                            openURL:options:completionHandler:
In module 'UIKit' imported from /Users/lo/Library/Developer/Xcode/DerivedData/bepatient-csfxukfrxvcjecbmrqpffuxhrgys/Build/Products/Debug-iphonesimulator/include/Cordova/CDVAvailabilityDeprecated.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
- (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
^
/Users/lo/dev/app-ionic/bepatient-app/platforms/ios/bepatient/Plugins/cordova-plugin-phone-call/PhoneDialer.m:126:23: warning: unused variable 'appChooser' [-Wunused-variable]
            NSString* appChooser = [command.arguments objectAtIndex:1];
                      ^
5 warnings and 9 errors generated.
`

How can I help you fix this issue ?

**Comment by lakshmansha** [comment]
Hi Loran,

We are currently working on it. At Present Please use the v1.0.7.

**Comment by lakshmansha** [comment]
Hi @loranBepatient ,

I have fixed the Plugin Please check & let us know.

**Comment by loranBepatient** [comment]
@lakshmansha Thank you. 

Your fix is working.
I successfully build the app with `cordova-plugin-phone-call` 1.1.3 

👏

**Comment by lakshmansha** [comment]
Good to Hear @loranBepatient . 

If you have suggestion for Feature. Please let us know.
